### ISSUE TITLE
could not run npm install -g nova-generator

### ISSUE THREAD

**Issue by adrien59cadri** [NovaeWorkshop/Nova#18]
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'nova-generator' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\adrien\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\adrien\AppData\Roaming\npm\package.json
6 silly cache add args [ 'nova-generator', null ]
7 verbose cache add spec nova-generator
8 silly cache add parsed spec { raw: 'nova-generator',
8 silly cache add   scope: null,
8 silly cache add   name: 'nova-generator',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed nova-generator@*
10 verbose addNamed "*" is a valid semver range for nova-generator
11 silly addNameRange { name: 'nova-generator', range: '*', hasData: false }
12 silly mapToRegistry name nova-generator
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/nova-generator
16 verbose addNameRange registry:https://registry.npmjs.org/nova-generator not in flight; fetching
17 verbose request uri https://registry.npmjs.org/nova-generator
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:21:48 PM
20 verbose request id 3009315f8d6a91a5
21 http request GET https://registry.npmjs.org/nova-generator
22 http 404 https://registry.npmjs.org/nova-generator
23 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'content-length': '51',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Sun, 26 Jul 2015 13:21:55 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-lcy1130-LCY',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1437916915.111482,VS0,VE362' }
24 silly get cb [ 404,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'content-length': '51',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Sun, 26 Jul 2015 13:21:55 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-lcy1130-LCY',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1437916915.111482,VS0,VE362' } ]
25 verbose stack Error: 404 Not Found: nova-generator
25 verbose stack     at CachingRegistryClient.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:245:14)
25 verbose stack     at Request._callback (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
25 verbose stack     at Request.self.callback (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
25 verbose stack     at Request.emit (events.js:110:17)
25 verbose stack     at Request.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
25 verbose stack     at Request.emit (events.js:129:20)
25 verbose stack     at IncomingMessage.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
25 verbose stack     at IncomingMessage.emit (events.js:129:20)
25 verbose stack     at _stream_readable.js:908:16
25 verbose stack     at process._tickCallback (node.js:355:11)
26 verbose statusCode 404
27 verbose pkgid nova-generator
28 verbose cwd l:\
29 error Windows_NT 6.3.9600
30 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nova-generator"
31 error node v0.12.7
32 error npm  v2.11.3
33 error code E404
34 error 404 Not Found: nova-generator
34 error 404
34 error 404 'nova-generator' is not in the npm registry.
34 error 404 You should bug the author to publish it (or use the name yourself!)
34 error 404
34 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

**Comment by adrien59cadri** [comment]
Basically, juste the readme.md is wrong, because npm install -g generator-nova (instead of nova-generator) works,

**Comment by kube** [comment]
Thanks for reporting this!
